# Generated by Django 3.2.8 on 2021-10-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateTimeField(verbose_name='date published')),
                ('end_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250)),
                ('question_type', models.CharField(choices=[('TEXT', 'TEXT'), ('ONEOPTION', 'ONEOPTION'), ('MANYOPTION', 'MANYOPTION')], max_length=250)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.poll')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('option_text', models.CharField(max_length=250, null=True)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='api.option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll', to='api.poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='api.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
    ]
